table Customers
	excludeFromModelRefresh
	lineageTag: 0fe79edc-3ffe-43fe-a574-181d3811fb0a

	column customer_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f5d09bca-3618-4109-889d-7d200f9eca6c
		summarizeBy: none
		sourceColumn: customer_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column customer_acct_num
		dataType: string
		lineageTag: d589ed08-e0a3-4893-ba10-bbc13cb6453b
		summarizeBy: none
		sourceColumn: customer_acct_num

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: 887695bd-342e-40be-926e-84fec252d4ea
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: 8f38b77d-7803-46bc-913f-bdf12a307e6a
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column customer_address
		dataType: string
		lineageTag: 5ab442f6-35ac-453b-b23e-bbe5205a89f6
		summarizeBy: none
		sourceColumn: customer_address

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 541a6e4a-db61-4490-8970-dc9879a5cb65
		dataCategory: City
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state_province
		dataType: string
		lineageTag: 8380d182-fd5c-4046-a44f-03fdb928f383
		summarizeBy: none
		sourceColumn: customer_state_province

		annotation SummarizationSetBy = Automatic

	column customer_postal_code
		dataType: string
		lineageTag: 46b23ad9-f16b-4291-8067-7d228bc7f6b0
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: customer_postal_code

		annotation SummarizationSetBy = Automatic

	column customer_country
		dataType: string
		lineageTag: 7f744f1e-2e88-475a-a175-9f33bd897b10
		dataCategory: Country
		summarizeBy: none
		sourceColumn: customer_country

		annotation SummarizationSetBy = Automatic

	column birthdate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5f45eaa4-8a79-48d7-b9b3-bdcfe6a55ab3
		summarizeBy: none
		sourceColumn: birthdate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column marital_status
		dataType: string
		lineageTag: 25c7c4e0-d3a2-46f9-9a3a-2ac6acffdd38
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

	column yearly_income
		dataType: string
		lineageTag: 683e468b-8635-4d6b-92bf-0b2da8e0d332
		summarizeBy: none
		sourceColumn: yearly_income

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 003e8a60-a432-49aa-9cef-3c1cdb8c24ce
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column total_children
		dataType: int64
		formatString: 0
		lineageTag: 5d123e43-4726-41c1-89e5-731e21c1378a
		summarizeBy: sum
		sourceColumn: total_children

		annotation SummarizationSetBy = Automatic

	column num_children_at_home
		dataType: int64
		formatString: 0
		lineageTag: 3548ad86-a76a-4faa-8ed9-f1989c7ddeae
		summarizeBy: sum
		sourceColumn: num_children_at_home

		annotation SummarizationSetBy = Automatic

	column education
		dataType: string
		lineageTag: b959690a-b87b-47b8-8292-a88af8379cb4
		summarizeBy: none
		sourceColumn: education

		annotation SummarizationSetBy = Automatic

	column acct_open_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 172f3322-9ba6-4cb0-b37a-d01139d621f6
		summarizeBy: none
		sourceColumn: acct_open_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column member_card
		dataType: string
		lineageTag: 65a90cca-858f-4044-8b45-a99d87a777d3
		summarizeBy: none
		sourceColumn: member_card

		annotation SummarizationSetBy = Automatic

	column occupation
		dataType: string
		lineageTag: 3012a75b-301d-4783-b833-4d5d83402833
		summarizeBy: none
		sourceColumn: occupation

		annotation SummarizationSetBy = Automatic

	column homeowner
		dataType: string
		lineageTag: 81d771cf-4bc1-4cab-8eeb-432811d40a21
		summarizeBy: none
		sourceColumn: homeowner

		annotation SummarizationSetBy = Automatic

	column full_name = Customers[first_name] & " " & Customers[last_name]
		dataType: string
		lineageTag: f8e4822b-7943-4c05-9c5a-94e082c19314
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column birht_year = Customers[birthdate].[Year]
		dataType: string
		lineageTag: 3c58bb56-1e04-4ea8-aade-36e9f69ba599
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column has_children
		dataType: string
		lineageTag: 23e7e8d1-39ab-42a8-bf0e-04ff926b6b83
		summarizeBy: none
		sourceColumn: has_children

		annotation SummarizationSetBy = Automatic

	column 'Current Age' = DATEDIFF(Customers[birthdate], TODAY(),YEAR)
		formatString: 0
		lineageTag: 935c18df-cd91-4d8c-ba7a-0d6483e4262a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Priority = ```
			IF(Customers[homeowner] = "Y" && 
			Customers[member_card] = "Golden", 
			"High", 
			"Standard")
			```
		lineageTag: b6cdd752-0f24-4a8d-bcea-0ac1b9a8ac44
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Short_country =
			LEFT(
			    UPPER(Customers[customer_country]),3)
		lineageTag: f0e20c6f-e832-4ee8-a8bf-1704e56fcbbf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'House Number' =
			LEFT(Customers[customer_address],
			SEARCH( " ", Customers[customer_address], 1, BLANK()))
		lineageTag: 3c33a205-def4-40a0-ab8d-54c5b781ab59
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\milla\Downloads\Udemy\Power BI\Maven+Market+CSV+Files\MavenMarket_Customers.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"customer_acct_num", type text}, {"first_name", type text}, {"last_name", type text}, {"customer_address", type text}, {"customer_city", type text}, {"customer_state_province", type text}, {"customer_postal_code", type text}, {"customer_country", type text}, {"birthdate", type date}, {"marital_status", type text}, {"yearly_income", type text}, {"gender", type text}, {"total_children", Int64.Type}, {"num_children_at_home", Int64.Type}, {"education", type text}, {"acct_open_date", type date}, {"member_card", type text}, {"occupation", type text}, {"homeowner", type text}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "has_children", each if [total_children] = 0 then "N" else "Y")
				in
				    #"Added Conditional Column"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

